### ISSUE TITLE
Output naming and values are incorrect

### ISSUE THREAD

**Issue by Dipak-Mistry-WTW** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#14]
The output values do not reflect the names. For example both "id" and "workspace_id" have the same value (which returns all the attributes). Currently to get the value for the workspace id I have to use "module.module_name.id.id". I would suggest just one output like:

```
output "workspace" {
  description = "The log analytics workspace attributes."
  value       = azurerm_log_analytics_workspace.this
}
```

This would mean that using the output elsewhere I would be writing module.module_name.workspace.id which would be better more accurate naming and look nicer.

**Comment by cshea-msft** [comment]
Thanks for your feedback @Dipak-Mistry-WTW if you look at the example you can see how the module is called. The output naming is based on our templates.

**Comment by Dipak-Mistry-WTW** [comment]
@cshea-msft  - I am looking at the output example in the template.  The template suggests the naming is wrong here and the values are wrong. This is what the template has in outputs.

```
# Module owners should include the full resource via a 'resource' output
# https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tffr2---category-outputs---additional-terraform-outputs

output "resource" {
  description = "This is the full output for the resource."
  value       = azurerm_resource_group.TODO # TODO: Replace this dummy resource azurerm_resource_group.TODO with your module resource
}
```
So my example above would still better align with the template than what's currently there.
