### ISSUE TITLE
[AVM Module Issue]: Workspace Outputs Overwritten . Returning Object instead of Properties

### ISSUE THREAD

**Issue by boblarson-ka** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#19]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Module specific issue

- [X] I confirm that this issue is about this AVM module and not about the resource itself, or how to use Terraform.

### Issue Type?

Bug

### (Optional) Module Version

0.1.3

### Description

The commit from a week ago 19543b3fa444353f38bcd1ebd7124683e209f170 has the right references, but the Chore branch: https://github.com/Azure/terraform-azurerm-avm-res-operationalinsights-workspace/pull/18 brought over the object references vs the ones that were in the output correction branch.

I think I'm following the git flow of commits that this looks like an error pre generation of 0.1.3. If I'm mistaken, my apologies.

Expectations post fix is workspace_id reference the id and no longer the workspace object.

**Comment by cshea-msft** [comment]
Thanks for the feedback @boblarson-ka. Our formatting for the output is a little different than the Terraform Registry docs. There will be some updates to the next version release
