### ISSUE TITLE
[AVM Module Issue]: 

### ISSUE THREAD

**Issue by philipstreet** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#25]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.3

### Description

The output "workspace_id" returns the entire workspace resource, not the ID.

Current code is:

```
output "workspace_id" {
  description = "The Resource ID of the Log Analytics Workspace."
  value       = azurerm_log_analytics_workspace.this
}
```

Suggest to replace with:

```
output "workspace_id" {
  description = "The Resource ID of the Log Analytics Workspace."
  value       = azurerm_log_analytics_workspace.this.id
}
```

**Comment by philipstreet** [comment]
> @philipstreet workspace_id is different from the id. try resource.id
> 
> azurerm_log_analytics_workspace.resource.id
> 

We've moved over to doing that for all AVMs.

**Comment by cshea-msft** [comment]
> > @philipstreet workspace_id is different from the id. try resource.id
> > azurerm_log_analytics_workspace.resource.id
> 
> @cshea-msft We've moved over to doing that for all AVMs.

Sounds good! every module should have a resource output. I got some updates I am working on to clean up my outputs. We are still learning as we go. Thanks for the feedback!!  Keep it coming!
