### ISSUE TITLE
[AVM Question/Feedback]: Inconsistent outputs

### ISSUE THREAD

**Issue by philipstreet** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#29]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Why do all three outputs (name, resource & workspace_id) all return the same thing (the LAW resource), which does not seem to align with the spec (https://azure.github.io/Azure-Verified-Modules/specs/shared/#id-rmfr7---category-outputs---minimum-required-outputs)?

Can I suggest the following?

``` terraform
output "name" {
  description = "The Name of the Log Analytics Workspace."
  value       = azurerm_log_analytics_workspace.this.name
}

output "resource" {
  description = "The Log Analytics Workspace resource"
  value       = azurerm_log_analytics_workspace.this
}

output "resource_id" {
  description = "The Resource ID of the Log Analytics Workspace."
  value       = azurerm_log_analytics_workspace.this.id
}
```

I'm not sure workspace_id is really needed, given you could get that from the "resource" output.

**Comment by cshea-msft** [comment]
fixed in latest pr
