### ISSUE TITLE
[AVM Module Issue]: Capability to apply log_analytics_solutions as a child item to the workspace

### ISSUE THREAD

**Issue by ChrisSidebotham** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#40]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### (Optional) Module Version

0.1.5

### Description

In order to enable features like sentinel etc we should be able to apply log analytics solutions to the workspace. Discussion to have, should this be with this module or a seperate child module. Opening this issue to see if @cshea-msft is willing to be the owner

**Comment by cshea-msft** [comment]
@ChrisSidebotham - could add it as a sub-module to the LAW module? Since log analytics solution isn't a standalone resource.

**Comment by ChrisSidebotham** [comment]
To be discussed with core TF Team this week...

In bicep version we have a separate resource module as the Resource Provider is **not the same** as the resource provider for the Log analytics workspace. Therefore the module requires 2 inputs: 
 - Name
 - LAW Id

**Comment by matt-FFFFFF** [comment]
Sub modules are allowed for parent child resources. See the virtual network module.

References must be passed by resource id.

**Comment by cshea-msft** [comment]
@ChrisSidebotham @matt-FFFFFF @mbilalamjad  - To confirm I'll create the Log Analytics Solution as a Sub-Module for the Log Analytics Workspace Resource Module.

**Comment by matt-FFFFFF** [comment]
Is it definitely a child resource?

**Comment by cshea-msft** [comment]
Log Analytics Solution is dependent on LAW, it Requires a workspace ID to deploy the Solution so I would think Yes. IMO

**Comment by matt-FFFFFF** [comment]
I think in this case it makes sense to use a submodule. You can't deploy solutions anywhere else after all.

**Comment by cshea-msft** [comment]
log analytics solution sub module will added to the next version release.

**Comment by c-baumgartner** [comment]
I just wanted to know if this is still on the roadmap, because there are already a lot of version releases since this was closed 😄. I am currently creating a new service/solution and trying to build it out of 100% AVM Pattern/Resources modules. Sentinel is part of this solution, and I also need to deploy Solutions to the LWA.

**Comment by cshea-msft** [comment]
Hey @c-baumgartner  - the submodule was released. I apologize for any miscommunication. It is under module folder. I had to make it a sub-module. 
https://github.com/Azure/terraform-azurerm-avm-res-operationalinsights-workspace/tree/main/modules/log_analytics_solution and here is an example i created. https://github.com/Azure/terraform-azurerm-avm-res-operationalinsights-workspace/tree/main/examples/deploy_security_insights 

Hope this helps. if any issues please open an issue and link this issue.

**Comment by c-baumgartner** [comment]
Thank you for the quick response @cshea-msft - I did not see that one because there was no PR linked to this issue and I could not find any trace on the AVM side nor in the documentation for the "parent"-module.

Are there some thoughts on how this will be documented / communicated for similar cases? I also had to check on how to pull a submodule directly from the registry :-)

Just in case someone struggles with that here is a module call:

```hcl
module "log_analytics_solution" {
  source  = "Azure/avm-res-operationalinsights-workspace/azurerm//modules/log_analytics_solution"
  version = "0.4.1"
  ...
```

**Comment by cshea-msft** [comment]
> Thank you for the quick response [@cshea-msft](https://github.com/cshea-msft) - I did not see that one because there was no PR linked to this issue and I could not find any trace on the AVM side nor in the documentation for the "parent"-module.
> 
> And I did not pay close attention in the registry that there is a submodule :-D

Yes, that is my fault, I didn't communicate well.
