### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by segraef** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#6]
https://github.com/Azure/terraform-azurerm-avm-res-operationalinsights-workspace/blob/59cf96d72638b5ce21e4c1ff7f9582ab475f36de/README.md?plain=1#L234 shouldn't be key vault/

credits go to @acauret

**Comment by cshea-msft** [comment]
@segraef  typo has been fixed and PR has been pushed with new version.
