### ISSUE TITLE
[AVM Module Issue]: modtm provider version error

### ISSUE THREAD

**Issue by Dipak-Mistry-WTW** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#68]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.3.1

### Description

When initiallising terraform i get the following:

```
Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/modtm: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/modtm
```

Is the correct "required" provider version listed?

**Comment by cshea-msft** [comment]
@Dipak-Mistry-WTW thank you for the feedback, use the latest version 0.3.2
