### ISSUE TITLE
[AVM Module Issue]: output 'resource' is seen as sensitive but not marked as which errors out the module

### ISSUE THREAD

**Issue by mrozenbeekBudgetThuis** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#74]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.3.3

### Description

I use this module but it keeps failing on this:

![image](https://github.com/user-attachments/assets/29ddd8cc-5fca-4df0-b5e7-867d12606250)

i use the resource_id output but in our case terraform run via terragrunt fails on the above exception. I looked into other modules and they seem to have sensitive=true on the resource output.

If i'm correct we need to set it in this module as well.

**Comment by mrozenbeekBudgetThuis** [comment]
i'm more then happy to make the PR if that makes it easier.

**Comment by cshea-msft** [comment]
@mrozenbeekBudgetThuis thanks for the issue. yes feel free to create a PR to add. Thanks!

**Comment by mrozenbeekBudgetThuis** [comment]
@cshea-msft i created a PR #75

**Comment by cshea-msft** [comment]
@mrozenbeekBudgetThuis sorry for the confusion but i will need to create a PR so i can run the formatting command. Dont want to add that to your to do. It will be in version 0.3.3
