### ISSUE TITLE
[AVM Module Issue]: support for attaching to AMPLS

### ISSUE THREAD

**Issue by rbradley51** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#77]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Please add support for attaching to an existing AMPLS.

supporting two connection scenarios; same subscription & cross subscription.

Thank you

**Comment by cshea-msft** [comment]
thanks for the feedback @rbradley51 I can definitely look at adding these solutions but will take some time. If you are interested you are more than welcome to create a fork and update the content.

**Comment by rbradley51** [comment]
@cshea-msft to support attaching to an existing AMPLS, I've been using this:

```hcl
resource "azapi_resource" "ampls" {
  type = "Microsoft.Insights/privateLinkScopes/scopedResources@2021-07-01-preview"
  for_each = var.monitor_private_link_scoped_resource

  name          = each.value.name != null ? each.value.name : azurerm_log_analytics_workspace.this.name
  parent_id     = each.value.resource_id
  ignore_casing = true
  
  body = jsonencode({
    properties = {
      linkedResourceId = azurerm_log_analytics_workspace.this.id
    }
  })
  
}
```

```hcl
variable "monitor_private_link_scoped_resource" {
  type = map(object({
    name        = optional(string)
    resource_id = string
  }))
  default     = {}
  description = <<DESCRIPTION
 - `name` - Defaults to the name of the Log Analytics Workspace.
 - `resource_id` - Resource ID of an existing Monitor Private Link Scope to connect to.
DESCRIPTION
}
```

it can be done with `azurerm_monitor_private_link_scoped_service` but requires passing a provider alias to the module for cross sub connections.
