### ISSUE TITLE
[AVM Module Issue]: add support for Azure Provider v4.0

### ISSUE THREAD

**Issue by chopeen** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#82]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

Modify the module to support `azurerm` v4 (see [4.0-upgrade-guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide) for change log and migration hints).

**Comment by cshea-msft** [comment]
added azurerm v4.0
