### ISSUE TITLE
[AVM Module Issue]: private endpoint not getting created for latest version of the module

### ISSUE THREAD

**Issue by Gopinadh-Parsagani** [Azure/terraform-azurerm-avm-res-operationalinsights-workspace#85]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

**Comment by Gopinadh-Parsagani** [comment]
close it

**Comment by cshea-msft** [comment]
this will be fixed in the next release

**Comment by cshea-msft** [comment]
fixed in latest release v0.4.0. Review deploy_network_isolation example.

**Comment by Gopinadh-Parsagani** [comment]
Hi @cshea-msft,

You are creating the wrong private DNS for the linked scope. It is looking for a few DNS entries. Please find the below screen prints for reference

![image](https://github.com/user-attachments/assets/d71c5abf-cf19-4c08-b82e-1b4140e44012)

![image](https://github.com/user-attachments/assets/d52a0965-8e1e-4dff-aed7-cdeaf781b0be)

![image](https://github.com/user-attachments/assets/e0d40f50-b266-4614-9415-8097c149ecca)

**Comment by cshea-msft** [comment]
good catch, fixed it in the v0.4.1

**Comment by Gopinadh-Parsagani** [comment]
Hi @cshea-msft ,
Still it is not working!!. Could you create it manually first and then think about how you can automate it? No records are getting created under the DNS

**Comment by cshea-msft** [comment]
This is what i see when i run my example. Its just an example you can tweak it how you want. 

![image](https://github.com/user-attachments/assets/0aba1193-0148-44e3-89df-b05739101fc5)
